// Fictional sample data from PLAN.md §14. Never put real contacts here.
import type { Data } from './types'

function at(daysFromNow: number, hour = 12, minute = 0) {
  const d = new Date()
  d.setDate(d.getDate() + daysFromNow)
  d.setHours(hour, minute, 0, 0)
  return d.toISOString()
}

export function createSampleData(): Data {
  return {
    activeEvent: null,
    events: [
      {
        id: 'ev1',
        name: 'Business meetup',
        place: 'South Charlotte',
        date: at(-8, 18),
        endsAt: at(-7, 0),
      },
      {
        id: 'ev2',
        name: 'Founders coffee',
        place: 'Plaza Midwood',
        date: at(-1, 18),
        endsAt: at(0, 0),
      },
    ],
    ideas: [
      {
        id: 'i1',
        name: 'Document collection tool for bookkeepers',
        description: 'Help high-volume bookkeeping and tax practices get documents and signatures from clients without the chasing.',
        status: 'building-evidence',
        keyQuestions: [
          'Tell me about the last time a client was late with documents. What happened and what did it cost?',
          'What have you tried or paid for to fix it, and why did it stick or not?',
          'What do clients need to sign, and how do you handle that today?',
        ],
      },
      {
        id: 'i2',
        name: 'Lead generation for local service businesses',
        description: 'Cleaning companies, bookkeepers and accountants who need a steady flow of new clients.',
        status: 'exploring',
        keyQuestions: [
          'Where did your last few new clients come from?',
          'When someone asks for a quote, who responds and how fast?',
          'Have you paid for marketing before, and what happened?',
        ],
      },
      {
        id: 'i3',
        name: 'Job checklist for cleaning companies',
        description: 'Quality control and proof of work for small, new cleaning businesses.',
        status: 'exploring',
        keyQuestions: [
          'What happens today when a cleaner misses something?',
          'Is the checklist for training, quality control, or showing clients?',
          'How do you and your cleaners communicate during a job?',
        ],
      },
    ],
    beliefs: [
      { id: 'b1', ideaId: 'i1', statement: 'Bookkeepers lose significant time chasing client documents during tax season.' },
      { id: 'b2', ideaId: 'i1', statement: 'Email is “good enough” for low-volume firms; the pain grows with client volume.' },
      { id: 'b3', ideaId: 'i1', statement: 'Needing client signatures is a key missing piece.' },
      { id: 'b4', ideaId: 'i2', statement: 'Small service owners’ biggest problem is getting more clients.' },
      { id: 'b5', ideaId: 'i2', statement: 'Many lose leads by responding slowly.' },
      { id: 'b6', ideaId: 'i3', statement: 'Owners need quality control and proof of work, not just a printed list.' },
    ],
    people: [
      {
        id: 'p1',
        name: 'Sam Rivera',
        hookLine: 'Owns a 6-person cleaning company, second year in business',
        role: 'Owner',
        company: 'Rivera Clean Co.',
        email: 'sam@example.com',
        personalNotes: 'Two kids, coaches Saturday soccer. Loves smoked brisket.',
        stage: 'acquaintance',
        flags: [],
        ideaIds: ['i3', 'i2'],
        eventId: 'ev1',
        metAt: at(-8, 19),
        needsTriage: false,
        source: 'capture',
      },
      {
        id: 'p2',
        name: 'Jordan Blake',
        hookLine: 'Says “finance,” wanted to grab coffee',
        role: 'Financial advisor',
        company: 'Summit Partners',
        stage: 'acquaintance',
        flags: ['pitching-me'],
        ideaIds: [],
        eventId: 'ev1',
        metAt: at(-8, 20),
        needsTriage: false,
        source: 'capture',
      },
      {
        id: 'p3',
        name: 'Priya Shah',
        hookLine: 'Bookkeeper, 80+ clients, dreads February',
        role: 'Founder',
        company: 'Shah Bookkeeping',
        email: 'priya@example.com',
        phone: '(704) 555-0142',
        personalNotes: 'Runs half marathons. Moved from Atlanta in 2022.',
        stage: 'contact',
        flags: ['great-connector'],
        ideaIds: ['i1'],
        eventId: 'ev1',
        metAt: at(-8, 19, 30),
        introducedBy: 'Sam Rivera',
        needsTriage: false,
        followUpAt: at(-1, 9),
        source: 'capture',
      },
      {
        id: 'p4',
        name: 'Guy in blue jacket',
        hookLine: 'Cleaning biz, just hired his 3rd cleaner, ex-bioengineer',
        stage: 'stranger',
        flags: [],
        ideaIds: [],
        eventId: 'ev2',
        metAt: at(-1, 19, 10),
        needsTriage: true,
        source: 'capture',
      },
      {
        id: 'p5',
        name: 'Maya',
        hookLine: 'Runs a 3-person tax prep office, uses email + Dropbox for docs',
        stage: 'stranger',
        flags: [],
        ideaIds: [],
        eventId: 'ev2',
        metAt: at(-1, 19, 40),
        needsTriage: true,
        source: 'capture',
      },
      {
        id: 'p6',
        name: 'Devon Okafor',
        hookLine: 'Runs the South Charlotte meetup, knows everyone',
        role: 'Organizer',
        company: 'CLT Small Biz Network',
        stage: 'contact',
        flags: ['great-connector'],
        ideaIds: ['i2'],
        eventId: 'ev1',
        metAt: at(-8, 18, 30),
        needsTriage: false,
        followUpAt: at(2, 9),
        source: 'manual',
      },
    ],
    meetings: [
      {
        id: 'm1',
        personId: 'p3',
        status: 'debriefed',
        at: at(-4, 10),
        type: 'coffee',
        intent: 'Wants to hear about the document tool idea',
        questions: [
          {
            text: 'Tell me about the last time a client was late with documents. What happened and what did it cost?',
            progress: 'answered',
            note: 'Last March, 11 clients late. She worked two weekends and filed 4 extensions.',
          },
          {
            text: 'What have you tried or paid for to fix it, and why did it stick or not?',
            progress: 'answered',
            note: 'Tried a client portal ($40/mo). Clients never logged in. Back to email.',
          },
          {
            text: 'What do clients need to sign, and how do you handle that today?',
            progress: 'partly',
            note: 'Engagement letters and 8879s. Uses DocuSign separately, didn’t get into cost.',
          },
        ],
        takeaways: [
          'The portal failed because clients won’t create accounts.',
          'She loses about two weekends every tax season to chasing.',
          'Signatures are a separate tool today and she hates switching.',
        ],
        honesty: { gotFacts: true, pitchedTooEarly: false, theyPitchedMe: false },
        notes: 'Very direct. Offered to intro me to two other bookkeepers.',
      },
      {
        id: 'm2',
        personId: 'p2',
        status: 'debriefed',
        at: at(-5, 8, 30),
        type: 'coffee',
        intent: '',
        questions: [],
        takeaways: [
          'It was a recruitment pitch for his firm.',
          'Nothing relevant to any of my ideas.',
          'Next time, ask what the meeting is for first.',
        ],
        honesty: { gotFacts: false, pitchedTooEarly: false, theyPitchedMe: true },
        notes: '',
      },
      {
        id: 'm3',
        personId: 'p1',
        status: 'planned',
        at: at(2, 15),
        type: 'coffee',
        intent: 'Talk about how he runs jobs and finds clients',
        questions: [
          { text: 'What happens today when a cleaner misses something?', progress: 'not-asked', note: '' },
          { text: 'Is the checklist for training, quality control, or showing clients?', progress: 'not-asked', note: '' },
          { text: 'Where did your last few new clients come from?', progress: 'not-asked', note: '' },
        ],
        takeaways: [],
        honesty: { gotFacts: null, pitchedTooEarly: null, theyPitchedMe: null },
        notes: '',
      },
      {
        id: 'm4',
        personId: 'p3',
        status: 'planned',
        at: at(6, 11),
        type: 'demo',
        intent: '20-minute demo of the document request flow',
        questions: [
          { text: 'Would her clients open a link without an account?', progress: 'not-asked', note: '' },
          { text: 'Who else in the firm would use it?', progress: 'not-asked', note: '' },
          { text: 'What would make her switch before next tax season?', progress: 'not-asked', note: '' },
        ],
        takeaways: [],
        honesty: { gotFacts: null, pitchedTooEarly: null, theyPitchedMe: null },
        notes: '',
      },
    ],
    signals: [
      { id: 's1', meetingId: 'm1', personId: 'p3', type: 'problem', text: '“Last March I had eleven clients late. I worked two weekends straight.”', ideaIds: ['i1'] },
      { id: 's2', meetingId: 'm1', personId: 'p3', type: 'workaround', text: 'Tried a $40/mo client portal. Clients never logged in, so she went back to email.', ideaIds: ['i1'] },
      { id: 's3', meetingId: 'm1', personId: 'p3', type: 'money', text: 'Pays for DocuSign separately. She decides all software purchases.', ideaIds: ['i1'] },
      { id: 's4', meetingId: 'm1', personId: 'p3', type: 'emotion', text: '“I dread February.”', ideaIds: ['i1'] },
      { id: 's5', meetingId: 'm1', personId: 'p3', type: 'noise', text: '“I would totally use something like that.”', ideaIds: ['i1'] },
      { id: 's6', meetingId: 'm1', personId: 'p3', type: 'mention', text: 'Knows two other bookkeepers with the same problem.', ideaIds: ['i1'] },
    ],
    nextSteps: [
      { id: 'n1', meetingId: 'm1', personId: 'p3', owner: 'them', type: 'time', description: '20-minute demo of the document request flow', dueAt: at(6, 11), done: false },
      { id: 'n2', meetingId: 'm1', personId: 'p3', owner: 'them', type: 'introduction', description: 'Intro to two other bookkeepers', dueAt: at(-1, 17), done: false },
      { id: 'n3', meetingId: 'm1', personId: 'p3', owner: 'me', type: 'time', description: 'Send demo invite and a short agenda', dueAt: at(0, 17), done: false },
      { id: 'n4', meetingId: 'm2', personId: 'p2', owner: 'me', type: 'none', description: '', done: true },
    ],
  }
}
