/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IdeasIndexRouteImport } from './routes/ideas.index'
import { Route as IdeasIdeaIdRouteImport } from './routes/ideas.$ideaId'
import { Route as MeetingsNewRouteImport } from './routes/meetings.new'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as PeoplePersonIdRouteImport } from './routes/people.$personId'
import { Route as MeetingsMeetingIdBriefRouteImport } from './routes/meetings.$meetingId.brief'
import { Route as MeetingsMeetingIdDebriefRouteImport } from './routes/meetings.$meetingId.debrief'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIndexRoute = IdeasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IdeasRoute,
} as any)
const IdeasIdeaIdRoute = IdeasIdeaIdRouteImport.update({
  id: '/$ideaId',
  path: '/$ideaId',
  getParentRoute: () => IdeasRoute,
} as any)
const MeetingsNewRoute = MeetingsNewRouteImport.update({
  id: '/meetings/new',
  path: '/meetings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PeopleRoute,
} as any)
const PeoplePersonIdRoute = PeoplePersonIdRouteImport.update({
  id: '/$personId',
  path: '/$personId',
  getParentRoute: () => PeopleRoute,
} as any)
const MeetingsMeetingIdBriefRoute = MeetingsMeetingIdBriefRouteImport.update({
  id: '/meetings/$meetingId/brief',
  path: '/meetings/$meetingId/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsMeetingIdDebriefRoute =
  MeetingsMeetingIdDebriefRouteImport.update({
    id: '/meetings/$meetingId/debrief',
    path: '/meetings/$meetingId/debrief',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/ideas': typeof IdeasRouteWithChildren
  '/inbox': typeof InboxRoute
  '/people': typeof PeopleRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/meetings/new': typeof MeetingsNewRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/ideas/': typeof IdeasIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/meetings/$meetingId/brief': typeof MeetingsMeetingIdBriefRoute
  '/meetings/$meetingId/debrief': typeof MeetingsMeetingIdDebriefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/inbox': typeof InboxRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/meetings/new': typeof MeetingsNewRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/ideas': typeof IdeasIndexRoute
  '/people': typeof PeopleIndexRoute
  '/meetings/$meetingId/brief': typeof MeetingsMeetingIdBriefRoute
  '/meetings/$meetingId/debrief': typeof MeetingsMeetingIdDebriefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/ideas': typeof IdeasRouteWithChildren
  '/inbox': typeof InboxRoute
  '/people': typeof PeopleRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/meetings/new': typeof MeetingsNewRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/ideas/': typeof IdeasIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/meetings/$meetingId/brief': typeof MeetingsMeetingIdBriefRoute
  '/meetings/$meetingId/debrief': typeof MeetingsMeetingIdDebriefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capture'
    | '/ideas'
    | '/inbox'
    | '/people'
    | '/settings'
    | '/sign-in'
    | '/ideas/$ideaId'
    | '/meetings/new'
    | '/people/$personId'
    | '/ideas/'
    | '/people/'
    | '/meetings/$meetingId/brief'
    | '/meetings/$meetingId/debrief'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capture'
    | '/inbox'
    | '/settings'
    | '/sign-in'
    | '/ideas/$ideaId'
    | '/meetings/new'
    | '/people/$personId'
    | '/ideas'
    | '/people'
    | '/meetings/$meetingId/brief'
    | '/meetings/$meetingId/debrief'
  id:
    | '__root__'
    | '/'
    | '/capture'
    | '/ideas'
    | '/inbox'
    | '/people'
    | '/settings'
    | '/sign-in'
    | '/ideas/$ideaId'
    | '/meetings/new'
    | '/people/$personId'
    | '/ideas/'
    | '/people/'
    | '/meetings/$meetingId/brief'
    | '/meetings/$meetingId/debrief'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptureRoute: typeof CaptureRoute
  IdeasRoute: typeof IdeasRouteWithChildren
  InboxRoute: typeof InboxRoute
  PeopleRoute: typeof PeopleRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  MeetingsNewRoute: typeof MeetingsNewRoute
  MeetingsMeetingIdBriefRoute: typeof MeetingsMeetingIdBriefRoute
  MeetingsMeetingIdDebriefRoute: typeof MeetingsMeetingIdDebriefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/': {
      id: '/ideas/'
      path: '/'
      fullPath: '/ideas/'
      preLoaderRoute: typeof IdeasIndexRouteImport
      parentRoute: typeof IdeasRoute
    }
    '/ideas/$ideaId': {
      id: '/ideas/$ideaId'
      path: '/$ideaId'
      fullPath: '/ideas/$ideaId'
      preLoaderRoute: typeof IdeasIdeaIdRouteImport
      parentRoute: typeof IdeasRoute
    }
    '/meetings/new': {
      id: '/meetings/new'
      path: '/meetings/new'
      fullPath: '/meetings/new'
      preLoaderRoute: typeof MeetingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/meetings/$meetingId/brief': {
      id: '/meetings/$meetingId/brief'
      path: '/meetings/$meetingId/brief'
      fullPath: '/meetings/$meetingId/brief'
      preLoaderRoute: typeof MeetingsMeetingIdBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/$meetingId/debrief': {
      id: '/meetings/$meetingId/debrief'
      path: '/meetings/$meetingId/debrief'
      fullPath: '/meetings/$meetingId/debrief'
      preLoaderRoute: typeof MeetingsMeetingIdDebriefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface IdeasRouteChildren {
  IdeasIdeaIdRoute: typeof IdeasIdeaIdRoute
  IdeasIndexRoute: typeof IdeasIndexRoute
}

const IdeasRouteChildren: IdeasRouteChildren = {
  IdeasIdeaIdRoute: IdeasIdeaIdRoute,
  IdeasIndexRoute: IdeasIndexRoute,
}

const IdeasRouteWithChildren = IdeasRoute._addFileChildren(IdeasRouteChildren)

interface PeopleRouteChildren {
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
}

const PeopleRouteChildren: PeopleRouteChildren = {
  PeoplePersonIdRoute: PeoplePersonIdRoute,
  PeopleIndexRoute: PeopleIndexRoute,
}

const PeopleRouteWithChildren =
  PeopleRoute._addFileChildren(PeopleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptureRoute: CaptureRoute,
  IdeasRoute: IdeasRouteWithChildren,
  InboxRoute: InboxRoute,
  PeopleRoute: PeopleRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  MeetingsNewRoute: MeetingsNewRoute,
  MeetingsMeetingIdBriefRoute: MeetingsMeetingIdBriefRoute,
  MeetingsMeetingIdDebriefRoute: MeetingsMeetingIdDebriefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
